"""empty message

Revision ID: 01184db55166
Revises: 60e3e91c6adb
Create Date: 2026-03-30 19:11:40.286157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01184db55166'
down_revision: Union[str, Sequence[str], None] = '60e3e91c6adb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_team_pokemon', sa.Column('level', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_team_pokemon', 'level')
    # ### end Alembic commands ###
