"""empty message

Revision ID: 1d6baf8399c0
Revises: 9e6118c5bb9c
Create Date: 2026-03-30 22:59:33.503812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d6baf8399c0'
down_revision: Union[str, Sequence[str], None] = '9e6118c5bb9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_team_pokemon', sa.Column('iv_hp', sa.Integer(), nullable=True))
    op.add_column('user_team_pokemon', sa.Column('iv_atk', sa.Integer(), nullable=True))
    op.add_column('user_team_pokemon', sa.Column('iv_def', sa.Integer(), nullable=True))
    op.add_column('user_team_pokemon', sa.Column('iv_spa', sa.Integer(), nullable=True))
    op.add_column('user_team_pokemon', sa.Column('iv_spd', sa.Integer(), nullable=True))
    op.add_column('user_team_pokemon', sa.Column('iv_spe', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_team_pokemon', 'iv_spe')
    op.drop_column('user_team_pokemon', 'iv_spd')
    op.drop_column('user_team_pokemon', 'iv_spa')
    op.drop_column('user_team_pokemon', 'iv_def')
    op.drop_column('user_team_pokemon', 'iv_atk')
    op.drop_column('user_team_pokemon', 'iv_hp')
    # ### end Alembic commands ###
