"""empty message

Revision ID: a4e2a6266096
Revises: 1d6baf8399c0
Create Date: 2026-03-30 23:13:44.652781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4e2a6266096'
down_revision: Union[str, Sequence[str], None] = '1d6baf8399c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('format_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['format_id'], ['formats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_team_pokemon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('species_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('ability_id', sa.Integer(), nullable=True),
    sa.Column('tera_type', sa.String(length=20), nullable=True),
    sa.Column('ev_hp', sa.Integer(), nullable=True),
    sa.Column('ev_atk', sa.Integer(), nullable=True),
    sa.Column('ev_def', sa.Integer(), nullable=True),
    sa.Column('ev_spa', sa.Integer(), nullable=True),
    sa.Column('ev_spd', sa.Integer(), nullable=True),
    sa.Column('ev_spe', sa.Integer(), nullable=True),
    sa.Column('nature', sa.String(length=20), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('iv_hp', sa.Integer(), nullable=True),
    sa.Column('iv_atk', sa.Integer(), nullable=True),
    sa.Column('iv_def', sa.Integer(), nullable=True),
    sa.Column('iv_spa', sa.Integer(), nullable=True),
    sa.Column('iv_spd', sa.Integer(), nullable=True),
    sa.Column('iv_spe', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ability_id'], ['abilities.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['species_id'], ['species.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['user_teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_team_pokemon_moves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pokemon_id', sa.Integer(), nullable=False),
    sa.Column('move_id', sa.Integer(), nullable=True),
    sa.Column('slot', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['move_id'], ['moves.id'], ),
    sa.ForeignKeyConstraint(['pokemon_id'], ['user_team_pokemon.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_team_pokemon_moves')
    op.drop_table('user_team_pokemon')
    op.drop_table('user_teams')
    # ### end Alembic commands ###
